services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan config:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: psql
          name: laravel-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromService:
          type: psql
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: psql
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: psql
          name: laravel-db
          property: password

databases:
  - name: laravel-db
    plan: free
